# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Dev-JonatanCL/POO_1/blob/main/Ol%C3%A1%2C_este_%C3%A9_o_Colaboratory.ipynb

#EX01
"""

F = float(input("Digite valor em Graus Farenheit: "))
C = (5/9)*(F-32)
print(f"O valor de {F}°F correspondente ao valor de {C}°C")

"""# EX02"""

P = float(input("Digite valor em Polegadas: "))
MM = P*25.4
print(f"O valor de {P}pol corresponde ao valor de {MM:1f}mm")

"""# EX03"""

idade = int(input("Digite sua idade: "))
if idade >= 18:
  print("Pode Votar")
else:
  print("Não pode Votar")
